let a = "♨︎"
let b = UnicodeScalar.init("\u{2668}")
let c = UnicodeScalar.init("\u{FE0E}")
let d = String.init(String.init(unicodeScalarLiteral: "\u{2668}\u{FE0E}\u{23B3}\u{FE04}"))
print(d?.characters.count)
print(d!.unicodeScalars.count)
//print(a.characters.map{$0})
//print(a.utf8.map{$0})
//print(a.utf16.map{$0})
//print(a.unicodeScalars.map{$0})
